version: '3.5'
services:
  api.case:
    image: case.backend:latest
    build: .
    container_name: api.case
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate && npm run start"
    networks:
      - backend
      - frontend
  db:
    image: postgres:12.3-alpine
    restart: always
    container_name: backend.db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ~/case_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    name: backend
  frontend:
    external: true
